spring:
  datasource:
    url: jdbc:mysql://localhost:3306/itemDb
    username: root
    password: Abhilasha@123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
  cache:
    type: redis
    redis:
      host: redis
      port: 6379
      time-to-live: 60000  # Cache expires in 60 seconds (adjust as needed)
server:
  port:
    8080
