## Spring Boot application configuration
#spring.datasource.url: jdbc:mysql://database:3306/itemDb
#spring.datasource.username: root
#spring.datasource.password: Abhilasha@123
#spring.jpa.hibernate.ddl-auto: update
#
#  # Redis Configuration
#spring.cache.type: redis
#spring.redis.host: cache
#spring.redis.port: 6379
#
#server.port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/itemDb
    username: root
    password: Abhilasha@123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
  cache:
    type: redis
    redis:
      host: redis
      port: 6379
server:
  port:
    8080
